<?php

use App\Middleware\CorsMiddleware;
use App\Middleware\SessionMiddleware;
use App\Support\JsonErrorHandler;
use DI\ContainerBuilder;
use Dotenv\Dotenv;
use Illuminate\Database\Capsule\Manager as Capsule;
use Slim\Factory\AppFactory;

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../app/Support/helpers.php';

$dotenv = Dotenv::createImmutable(dirname(__DIR__));
$dotenv->safeLoad();

date_default_timezone_set(env('APP_TIMEZONE', 'UTC'));

$containerBuilder = new ContainerBuilder();
$container = $containerBuilder->build();
AppFactory::setContainer($container);

$app = AppFactory::create();

$basePath = env('APP_BASE_PATH', '');
if ($basePath !== '') {
    $app->setBasePath($basePath);
}

$config = require __DIR__ . '/../config/database.php';
$capsule = new Capsule();
$capsule->addConnection($config);
$capsule->setAsGlobal();
$capsule->bootEloquent();

$dbTimezone = env('DB_TIMEZONE', null);
if ($dbTimezone) {
    $capsule->getConnection()->statement("SET time_zone = '{$dbTimezone}'");
}

$app->addBodyParsingMiddleware();
$app->add(new SessionMiddleware());

$errorMiddleware = $app->addErrorMiddleware((bool) env('APP_DEBUG', false), true, true);
$errorMiddleware->setDefaultErrorHandler(new JsonErrorHandler($app->getResponseFactory()));

// CorsMiddleware must be outermost so CORS headers are applied to ALL responses,
// including error responses generated by the error middleware.
$app->add(new CorsMiddleware());

(require __DIR__ . '/../app/Routes/api.php')($app);

return $app;
